FROM alpine-java:base
MAINTAINER baeldung.com
COPY target/CarApp-1.0-SNAPSHOT.jar /opt/CarApp/lib/

ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/CarApp/lib/CarApp-1.0-SNAPSHOT.jar"]
VOLUME /var/lib/CarApp/config-repo
EXPOSE 8080